Feat/TRPRO-5 add csv format
Ashampoo/Ashampoo-Translation-Systems pull request #73
Opened 2024-06-12 07:06 UTC by RealLHI

2024-06-25 06:49 UTC, tjorvenK requested changes

2024-06-25 06:49 UTC, tjorvenK commented on src/Ashampoo.Translation.Systems.Formats/src/CSV/CsvFormat.cs
> +            Comments = string.Join("|", translation.Comments)
Den '|' Character bitte über eine Konstante in der Klasse definieren

2024-06-25 06:49 UTC, tjorvenK commented on src/Ashampoo.Translation.Systems.Formats/src/CSV/CsvFormat.cs
> +internal record CsvRecordFormat
Der record kann glaube ich in den file scope verschoben werden (file record CsvRecord)

2024-06-25 06:49 UTC, tjorvenK commented on src/Ashampoo.Translation.Systems.Formats/src/CSV/CsvFormatHeader.cs
> +    public char Delimiter { get; set; } = ';';
Ist ';' der gängigste Separator? Ich dachte das ist ','

2024-06-25 06:49 UTC, tjorvenK commented on src/Ashampoo.Translation.Systems.Formats/src/CSV/CsvFormatBuilder.cs
> +        if (key is "delimiter")
Hier kannst du den delimiter direkt abspeichern und später in den CsvFormatHeader explizit einsetzen

2024-06-25 06:49 UTC, tjorvenK commented on src/Ashampoo.Translation.Systems.Formats/src/CSV/CsvFormatBuilder.cs
> +        else
Hier nicht throwen, sondern einfach nichts machen

2024-06-25 06:49 UTC, tjorvenK commented on src/Ashampoo.Translation.Systems.Formats/src/CSV/CsvFormatBuilder.cs
> +        _sourceLanguage = header.SourceLanguage ?? new Language("en-US");
Die Sprachen heir nicht überschreiben

2024-06-25 06:49 UTC, tjorvenK commented on src/Ashampoo.Translation.Systems.Formats/src/CSV/DependencyInjectionExtension.cs
> +        return services;
Hier fehlt noch die Injection, außerdem muss die Methode noch aufgerufen werden

2024-06-25 08:58 UTC, RealLHI commented on src/Ashampoo.Translation.Systems.Formats/src/CSV/CsvFormatHeader.cs
> +    public char Delimiter { get; set; } = ';';
Obsolete da diese Property nun keinen Standard Wert mehr hat. Wird jetzt entweder aus dem Header gelesen oder über die Options geholt.

2024-09-06 09:02 UTC, tjorvenK approved these changes

2024-09-06 09:02 UTC, merged